/* Generated By:JJTree: Do not edit this line. ASTLoopStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public class ASTLoopStatement extends StatementNode
{
    public ASTLoopStatement(int id)
    {
        super(id);
    }

    public ASTLoopStatement(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public int getLoopType()
    {
        return jjtGetFirstToken().kind;
    }
}
/* JavaCC - OriginalChecksum=2c344af21fb844d5a514639bcba5d47b (do not edit this line) */
