/* Generated By:JJTree: Do not edit this line. ASTPrefixIncrementOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTPrefixIncrementOperator extends OperatorNode {
  public ASTPrefixIncrementOperator(int id) {
    super(id);
  }

  public ASTPrefixIncrementOperator(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a789ffe73a1c0adb1ca8ace0d57757fb (do not edit this line) */
