/* Generated By:JJTree: Do not edit this line. ASTPostfixIncrementOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTPostfixIncrementOperator extends OperatorNode {
  public ASTPostfixIncrementOperator(int id) {
    super(id);
  }

  public ASTPostfixIncrementOperator(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=06214d012e34809e124d5a5e0662ad80 (do not edit this line) */
