/* Generated By:JJTree: Do not edit this line. ASTStatementBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.Parser;

public class ASTStatementBlock extends StatementNode
{
    public ASTStatementBlock(int id)
    {
        super(id);
    }

    public ASTStatementBlock(Parser p, int id)
    {
        super(p, id);
    }

    public ASTStatementBlock()
    {
        this(ParserTreeConstants.JJTSTATEMENTBLOCK);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=de3ae6a187ccf818b10d4480efc70c06 (do not edit this line) */
