/* Generated By:JJTree: Do not edit this line. ASTArgumentExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTArgumentExpression extends SimpleNode {
  public ASTArgumentExpression(int id) {
    super(id);
  }

  public ASTArgumentExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eccbc449693f3353ad4bfb2a8e47475e (do not edit this line) */
