/* Generated By:JJTree: Do not edit this line. ASTArgumentExpressionList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTArgumentExpressionList extends SimpleNode {
  public ASTArgumentExpressionList(int id) {
    super(id);
  }

  public ASTArgumentExpressionList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86ccea0dc381e3272c9c6d75d27ff340 (do not edit this line) */
