/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTArrayLiteral extends SimpleNode {
  public ASTArrayLiteral(int id) {
    super(id);
  }

  public ASTArrayLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a381bab72d48326ad726ad15f2e2d2db (do not edit this line) */
