/* Generated By:JJTree: Do not edit this line. ASTArithmeticExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTArithmeticExpression extends SimpleNode {
  public ASTArithmeticExpression(int id) {
    super(id);
  }

  public ASTArithmeticExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51adbfe37b48d49c0c38b9e8d210a07f (do not edit this line) */
