/* Generated By:JJTree: Do not edit this line. ASTArithmeticOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTArithmeticOperator extends SimpleNode {
  public ASTArithmeticOperator(int id) {
    super(id);
  }

  public ASTArithmeticOperator(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=013675a1771e109612526965f2291b99 (do not edit this line) */
