/* Generated By:JJTree: Do not edit this line. ASTAssignmentExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTAssignmentExpression extends SimpleNode {
  public ASTAssignmentExpression(int id) {
    super(id);
  }

  public ASTAssignmentExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58f4d6928e12295ab0c4d8d95b7ff3f8 (do not edit this line) */
