/* Generated By:JJTree: Do not edit this line. ASTBinaryAndExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTBinaryAndExpression extends SimpleNode {
  public ASTBinaryAndExpression(int id) {
    super(id);
  }

  public ASTBinaryAndExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f86c4549235b6ffbf9a67ff8c5b2bebb (do not edit this line) */
