/* Generated By:JJTree: Do not edit this line. ASTBinaryOrExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTBinaryOrExpression extends SimpleNode {
  public ASTBinaryOrExpression(int id) {
    super(id);
  }

  public ASTBinaryOrExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86a460a8debf20ec76099db7c5ceee2c (do not edit this line) */
