/* Generated By:JJTree: Do not edit this line. ASTCompoundExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTCompoundExpression extends SimpleNode {
  public ASTCompoundExpression(int id) {
    super(id);
  }

  public ASTCompoundExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21d662bf5a3c502fe48f5ec426176948 (do not edit this line) */
