/* Generated By:JJTree: Do not edit this line. ASTControlStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTControlStatement extends SimpleNode {
  public ASTControlStatement(int id) {
    super(id);
  }

  public ASTControlStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=495d2a7bf1e054423f98d7bd1a6f8cff (do not edit this line) */
