/* Generated By:JJTree: Do not edit this line. ASTConditionStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTConditionStatement extends SimpleNode {
  public ASTConditionStatement(int id) {
    super(id);
  }

  public ASTConditionStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67ae0c9c3768c6970d4469e9b175c101 (do not edit this line) */
