/* Generated By:JJTree: Do not edit this line. ASTConstant.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTConstant extends SimpleNode {
  public ASTConstant(int id) {
    super(id);
  }

  public ASTConstant(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=070eefcca0d4c6e2868a379205a9f091 (do not edit this line) */
