/* Generated By:JJTree: Do not edit this line. ASTClassBody.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8809c68e9125ce96157f47624bbfdb45 (do not edit this line) */
