/* Generated By:JJTree: Do not edit this line. ASTClassType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTClassType extends SimpleNode {
  public ASTClassType(int id) {
    super(id);
  }

  public ASTClassType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9da806e543387cbf1a4ae6b8b816fcf5 (do not edit this line) */
