/* Generated By:JJTree: Do not edit this line. ASTComparisonExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTComparisonExpression extends SimpleNode {
  public ASTComparisonExpression(int id) {
    super(id);
  }

  public ASTComparisonExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11a4759ad88eecf72526b2c607f93601 (do not edit this line) */
