/* Generated By:JJTree: Do not edit this line. ASTColon.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTColon extends SimpleNode {
  public ASTColon(int id) {
    super(id);
  }

  public ASTColon(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0e38917236f6b3a274b7ff2b82154c0 (do not edit this line) */
