/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTExclusiveOrExpression extends SimpleNode {
  public ASTExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTExclusiveOrExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce889b6f5792201e558654676e3337d4 (do not edit this line) */
