/* Generated By:JJTree: Do not edit this line. ASTFields.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFields extends SimpleNode {
  public ASTFields(int id) {
    super(id);
  }

  public ASTFields(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31ee6d8ef2a24b1b8bfd9fb620cb6bc4 (do not edit this line) */
