/* Generated By:JJTree: Do not edit this line. ASTFunctionSignature.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFunctionSignature extends SimpleNode {
  public ASTFunctionSignature(int id) {
    super(id);
  }

  public ASTFunctionSignature(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a3afa7bbbfebfeff9c3b7e45a3979fc (do not edit this line) */
