/* Generated By:JJTree: Do not edit this line. ASTFunctionArguments.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFunctionArguments extends SimpleNode {
  public ASTFunctionArguments(int id) {
    super(id);
  }

  public ASTFunctionArguments(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e6e8bf0b446466da0b15a8e39f033ba (do not edit this line) */
