/* Generated By:JJTree: Do not edit this line. ASTFunctionLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFunctionLiteral extends SimpleNode {
  public ASTFunctionLiteral(int id) {
    super(id);
  }

  public ASTFunctionLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba4e4619dd0eea86940922a65e9236c8 (do not edit this line) */
