/* Generated By:JJTree: Do not edit this line. ASTFile.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFile extends SimpleNode {
  public ASTFile(int id) {
    super(id);
  }

  public ASTFile(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f96bd5a7662429345dc7ae84f5fe9c39 (do not edit this line) */
