/* Generated By:JJTree: Do not edit this line. ASTFullType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTFullType extends SimpleNode {
  public ASTFullType(int id) {
    super(id);
  }

  public ASTFullType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c0fdf7b5a950ea80b994d813fe697cc (do not edit this line) */
