/* Generated By:JJTree: Do not edit this line. ASTHook.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTHook extends SimpleNode {
  public ASTHook(int id) {
    super(id);
  }

  public ASTHook(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37c04a9032936abb66cc2d1d9496012e (do not edit this line) */
