/* Generated By:JJTree: Do not edit this line. ASTIndexExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTIndexExpression extends SimpleNode {
  public ASTIndexExpression(int id) {
    super(id);
  }

  public ASTIndexExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=516eb612e93d86250f37d14ea81c82fe (do not edit this line) */
