/* Generated By:JJTree: Do not edit this line. ASTIndexPostfix.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTIndexPostfix extends SimpleNode {
  public ASTIndexPostfix(int id) {
    super(id);
  }

  public ASTIndexPostfix(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=857a0a8f595c5241392bac2680428c1a (do not edit this line) */
