/* Generated By:JJTree: Do not edit this line. ASTInherit.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTInherit extends SimpleNode {
  public ASTInherit(int id) {
    super(id);
  }

  public ASTInherit(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3861b3adf3d2131a08ba437ba5f04d00 (do not edit this line) */
