/* Generated By:JJTree: Do not edit this line. ASTLogicalAndExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTLogicalAndExpression extends SimpleNode {
  public ASTLogicalAndExpression(int id) {
    super(id);
  }

  public ASTLogicalAndExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc6c170b336921ecae82d544523b4885 (do not edit this line) */
