/* Generated By:JJTree: Do not edit this line. ASTLogicalOrExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTLogicalOrExpression extends SimpleNode {
  public ASTLogicalOrExpression(int id) {
    super(id);
  }

  public ASTLogicalOrExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b6eb2443f878a5a587fe138e9619ad2 (do not edit this line) */
