/* Generated By:JJTree: Do not edit this line. ASTLabel.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTLabel extends SimpleNode {
  public ASTLabel(int id) {
    super(id);
  }

  public ASTLabel(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1609b16b36861f0d89eeee8450ff98b9 (do not edit this line) */
