/* Generated By:JJTree: Do not edit this line. ASTLoopStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTLoopStatement extends SimpleNode {
  public ASTLoopStatement(int id) {
    super(id);
  }

  public ASTLoopStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c27757c0b3d7fe784367ff55dc2bd1b5 (do not edit this line) */
