/* Generated By:JJTree: Do not edit this line. ASTMappingLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTMappingLiteral extends SimpleNode {
  public ASTMappingLiteral(int id) {
    super(id);
  }

  public ASTMappingLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1b81733a6343aa9b0521360bb76e031 (do not edit this line) */
