/* Generated By:JJTree: Do not edit this line. ASTMappingElement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTMappingElement extends SimpleNode {
  public ASTMappingElement(int id) {
    super(id);
  }

  public ASTMappingElement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d311c954c74b6160c2d0e122aab2b10 (do not edit this line) */
