/* Generated By:JJTree: Do not edit this line. ASTModifiers.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9daeb752862385bd2cdddbedb855b973 (do not edit this line) */
