/* Generated By:JJTree: Do not edit this line. ASTParameterDeclarations.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTParameterDeclarations extends SimpleNode {
  public ASTParameterDeclarations(int id) {
    super(id);
  }

  public ASTParameterDeclarations(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f5ccb28c8e8665dfeb8c8b8ed6e56c5 (do not edit this line) */
