/* Generated By:JJTree: Do not edit this line. ASTScopeResolution.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTScopeResolution extends SimpleNode {
  public ASTScopeResolution(int id) {
    super(id);
  }

  public ASTScopeResolution(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df4bd7874f369cd721536d4db4d7238f (do not edit this line) */
