/* Generated By:JJTree: Do not edit this line. ASTStatementBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTStatementBlock extends SimpleNode {
  public ASTStatementBlock(int id) {
    super(id);
  }

  public ASTStatementBlock(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1fe3cdb1a4c2b08830e663df6dc0abca (do not edit this line) */
