/* Generated By:JJTree: Do not edit this line. ASTStandardTypeName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTStandardTypeName extends SimpleNode {
  public ASTStandardTypeName(int id) {
    super(id);
  }

  public ASTStandardTypeName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d901b099b1dfe169d834dfecb9bc04b2 (do not edit this line) */
