/* Generated By:JJTree: Do not edit this line. ASTTernaryExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTTernaryExpression extends SimpleNode {
  public ASTTernaryExpression(int id) {
    super(id);
  }

  public ASTTernaryExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=895624bbc0233c8b4c1880ca2f458243 (do not edit this line) */
