/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public
class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49d98d238207d9befe5b9e28d6fe3e7f (do not edit this line) */
