/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.2 */
package us.terebi.lang.lpc.parser.ast;

import us.terebi.lang.lpc.parser.jj.*;

public interface ParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTINHERIT = 1;
  public int JJTDECLARATION = 2;
  public int JJTFIELDS = 3;
  public int JJTVARIABLE = 4;
  public int JJTMETHOD = 5;
  public int JJTFUNCTIONSIGNATURE = 6;
  public int JJTMODIFIERS = 7;
  public int JJTTYPE = 8;
  public int JJTSTANDARDTYPENAME = 9;
  public int JJTCLASSTYPE = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTPARAMETERDECLARATIONS = 12;
  public int JJTPARAMETERDECLARATION = 13;
  public int JJTFULLTYPE = 14;
  public int JJTVOID = 15;
  public int JJTCLASSBODY = 16;
  public int JJTSTATEMENTBLOCK = 17;
  public int JJTSTATEMENT = 18;
  public int JJTLABEL = 19;
  public int JJTCONDITIONSTATEMENT = 20;
  public int JJTLOOPSTATEMENT = 21;
  public int JJTCONTROLSTATEMENT = 22;
  public int JJTVARIABLEDECLARATION = 23;
  public int JJTCOMPOUNDEXPRESSION = 24;
  public int JJTASSIGNMENTEXPRESSION = 25;
  public int JJTASSIGNMENTOPERATOR = 26;
  public int JJTTERNARYEXPRESSION = 27;
  public int JJTHOOK = 28;
  public int JJTCOLON = 29;
  public int JJTLOGICALOREXPRESSION = 30;
  public int JJTLOGICALANDEXPRESSION = 31;
  public int JJTBINARYOREXPRESSION = 32;
  public int JJTEXCLUSIVEOREXPRESSION = 33;
  public int JJTBINARYANDEXPRESSION = 34;
  public int JJTCOMPARISONEXPRESSION = 35;
  public int JJTCOMPARISONOPERATOR = 36;
  public int JJTARITHMETICEXPRESSION = 37;
  public int JJTARITHMETICOPERATOR = 38;
  public int JJTCASTEXPRESSION = 39;
  public int JJTUNARYEXPRESSION = 40;
  public int JJTUNARYOPERATOR = 41;
  public int JJTPOSTFIXEXPRESSION = 42;
  public int JJTSCOPERESOLUTION = 43;
  public int JJTINDEXPOSTFIX = 44;
  public int JJTINDEXEXPRESSION = 45;
  public int JJTFUNCTIONARGUMENTS = 46;
  public int JJTARGUMENTEXPRESSIONLIST = 47;
  public int JJTARGUMENTEXPRESSION = 48;
  public int JJTCONSTANT = 49;
  public int JJTARRAYLITERAL = 50;
  public int JJTARRAYELEMENT = 51;
  public int JJTMAPPINGLITERAL = 52;
  public int JJTMAPPINGELEMENT = 53;
  public int JJTFUNCTIONLITERAL = 54;


  public String[] jjtNodeName = {
    "File",
    "Inherit",
    "Declaration",
    "Fields",
    "Variable",
    "Method",
    "FunctionSignature",
    "Modifiers",
    "Type",
    "StandardTypeName",
    "ClassType",
    "Identifier",
    "ParameterDeclarations",
    "ParameterDeclaration",
    "FullType",
    "void",
    "ClassBody",
    "StatementBlock",
    "Statement",
    "Label",
    "ConditionStatement",
    "LoopStatement",
    "ControlStatement",
    "VariableDeclaration",
    "CompoundExpression",
    "AssignmentExpression",
    "AssignmentOperator",
    "TernaryExpression",
    "Hook",
    "Colon",
    "LogicalOrExpression",
    "LogicalAndExpression",
    "BinaryOrExpression",
    "ExclusiveOrExpression",
    "BinaryAndExpression",
    "ComparisonExpression",
    "ComparisonOperator",
    "ArithmeticExpression",
    "ArithmeticOperator",
    "CastExpression",
    "UnaryExpression",
    "UnaryOperator",
    "PostfixExpression",
    "ScopeResolution",
    "IndexPostfix",
    "IndexExpression",
    "FunctionArguments",
    "ArgumentExpressionList",
    "ArgumentExpression",
    "Constant",
    "ArrayLiteral",
    "ArrayElement",
    "MappingLiteral",
    "MappingElement",
    "FunctionLiteral",
  };
}
/* JavaCC - OriginalChecksum=592be2c786e9c6ca9d3a8a945cf07e44 (do not edit this line) */
