package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/complex.c */
public class complex extends LpcObject
{
/* Inheritance */
    public @us.terebi.lang.lpc.runtime.jvm.LpcInherited(name="sword", lpc="/std/lib/weapons/sword.c", implementation="us.terebi.lang.lpc.compiler.java.test.SwordTestObject")
    InheritedObject<us.terebi.lang.lpc.compiler.java.test.SwordTestObject> inherit_sword;

/* Members */

/* Field dwarf_kill (Line:5) */    
    public @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="dwarf_kill", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PRIVATE}) 
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.INT, depth=0) 
    final LpcField _f_dwarf_kill = new LpcField( "dwarf_kill", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.INT, 0) );

/* Method create (Line:7) */
    public @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="create", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PUBLIC}) 
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.VOID, depth=0) LpcValue 
    create_( )
    {
        final LpcValue _lpc_v1 = inherit_sword.get().create();
        final LpcValue _lpc_v2 = makeValue("shortsword");
        final LpcValue _lpc_v3 = inherit_sword.get().inherit_object.get().set_name(_lpc_v2);
        final LpcValue _lpc_v4 = makeValue("dwarven shortsword");
        final LpcValue _lpc_v5 = inherit_sword.get().inherit_object.get().add_alias(_lpc_v4);
        final LpcValue _lpc_v6 = makeValue("dwarven");
        final LpcValue _lpc_v7 = inherit_sword.get().inherit_object.get().add_alias(_lpc_v6);

        final LpcValue _lpc_v8 = makeValue("dwarven shortsword");
        final LpcValue _lpc_v9 = inherit_sword.get().inherit_object.get().set_short(_lpc_v8);

        final LpcValue _lpc_v10 = makeValue("This is a small iron sword\u002e There are strange dwarven markings on the blade\u002c but they are too faint to read");
        final LpcValue _lpc_v11 = inherit_sword.get().inherit_object.get().set_long(_lpc_v10);

        final LpcValue _lpc_v12 = makeValue(7);
        final LpcValue _lpc_v13 = inherit_sword.get().inherit_object.get().set_weight(_lpc_v12);

        final LpcValue _lpc_v14 = makeValue(10);
        final LpcValue _lpc_v15 = inherit_sword.get().set_wc(_lpc_v14);

        final LpcValue _lpc_v16 = new us.terebi.lang.lpc.runtime.jvm.LpcFunction(getObjectInstance(),1) {
            public LpcValue execute(List<? extends LpcValue> args) {
                final LpcValue _lpc_v17 = makeValue("get_race");
                final LpcValue _lpc_v18 = efun("call_other").execute(getArg(args, 1) , _lpc_v17 , makeArray());
                final LpcValue _lpc_v19 = makeValue("dwarf");
                final LpcValue _lpc_v20 = ComparisonSupport.equal(_lpc_v18,_lpc_v19);
                final LpcValue _lpc_v21;
                if( _lpc_v20.asBoolean() ) {
                    final LpcValue _lpc_v22 = makeValue(4);
                    _lpc_v21 = _lpc_v22;
                } else {
                    final LpcValue _lpc_v23 = MathSupport.negate(_f_dwarf_kill.get());
                    _lpc_v21 = _lpc_v23;
                }
                return _lpc_v21;
            } /* _lpc_v16.execute() */
        }; /* _lpc_v16 */
        final LpcValue _lpc_v24 = inherit_sword.get().add_wc_bonus(_lpc_v16);

        return makeValue();
    } 

/* Method target_killed (Line:22) */
    public @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="target_killed", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PROTECTED}) 
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.VOID, depth=0) LpcValue 
    target_killed_( @us.terebi.lang.lpc.runtime.jvm.LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, depth=0, name="target", semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.BY_VALUE) LpcValue _p_target_v )
    {
        final LpcVariable _p_target = new LpcVariable( "target", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, 0) , _p_target_v);
        final LpcValue _lpc_v25 = makeValue("get_race");
        final LpcValue _lpc_v26 = efun("call_other").execute(_p_target.get() , _lpc_v25 , makeArray());
        final LpcValue _lpc_v27 = makeValue("dwarf");
        final LpcValue _lpc_v28 = ComparisonSupport.equal(_lpc_v26,_lpc_v27);
        if( _lpc_v28.asBoolean() ) {
            final LpcValue _lpc_v29 = _f_dwarf_kill.get();
            _f_dwarf_kill.set(MathSupport.add(1,_lpc_v29));
        } // (if _lpc_v28)
        /* 'if'@24.5 */
        return makeValue();
    }
}

