package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/field.c */
public class field extends LpcObject
{
/* Inheritance */
/* Members */

/* Field ticks (Line:2) */
    public 
    @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="ticks", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.NOSAVE})
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.INT, depth=0)
    final LpcField _f_ticks = new LpcField("ticks", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.INT, 0));
}

