package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/field.c */
public class field extends LpcObject
{
    public final LpcField _f_ticks = new LpcField( "ticks", 
            withModifiers(us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.NOSAVE) ,
            withType( us.terebi.lang.lpc.runtime.LpcType.Kind.INT, 0)
        );
}

