package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/inherit.c */
public class inherit extends LpcObject
{
    public @LpcInherited(name="object", lpc="/std/lib/object.c", implementation="us.terebi.lang.lpc.compiler.java.test.ObjectTestObject")
    InheritedObject<us.terebi.lang.lpc.compiler.java.test.ObjectTestObject> inherit_object = loadInherited(us.terebi.lang.lpc.compiler.java.test.ObjectTestObject.class);

}

