package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/ref.c */
public class ref extends LpcObject
{
    public @LpcMethod(name="fuzz", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PRIVATE}) 
    @LpcReturn(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.MIXED, depth=0)
    LpcValue fuzz_( @LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, depth=0, name="s", 
                                    semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.EXPLICIT_REFERENCE) LpcReferenceValue _p_s_r )
    {
        final LpcReference _p_s = _p_s_r;
        final LpcValue _lpc_v1 = makeValue("!");
        _p_s.set(_lpc_v1);
    }
        
    public @LpcMethod(name="hoozit", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PUBLIC}) 
    @LpcReturn(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.MIXED, depth=1)
    LpcValue hoozit_( @LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, depth=0, name="s", semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.BY_VALUE) LpcValue _p_s_v
                             , @LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, depth=0, name="o", semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.BY_VALUE) LpcValue _p_o_v )
    {
        final LpcVariable _p_s = new LpcVariable( "s", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, 0) , _p_s_v);
        final LpcVariable _p_o = new LpcVariable( "o", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, 0) , _p_o_v);
        final LpcValue _lpc_v1 = fuzz_(new ReferenceValue(_p_s));
        final LpcValue _lpc_v2 = MathSupport.add(_p_s.get(), _p_o.get());
        return _lpc_v2;
    } 
}

