package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/ref.c */
public class ref extends LpcObject
{
/* Inheritance */
/* Members */

/* Method fuzz (Line:2) */
    public @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="fuzz", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PRIVATE}) 
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.MIXED, depth=0)
    LpcValue fuzz_( @us.terebi.lang.lpc.runtime.jvm.LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, depth=0, name="s", 
                                    semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.EXPLICIT_REFERENCE) LpcValue _p_s_v )
    {
        final LpcReference _p_s;
        if( _p_s_v instanceof LpcReference ) _p_s =  (LpcReference)_p_s_v;
        else _p_s = new LpcVariable( "s", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, 0) , _p_s_v);
        final LpcValue _lpc_v1 = makeValue("\u0021");
        _p_s.set(_lpc_v1);
        return _p_s.get();
    }
        
/* Method hoozit (Line:8) */
    public @us.terebi.lang.lpc.runtime.jvm.LpcMember(name="hoozit", modifiers={us.terebi.lang.lpc.runtime.MemberDefinition.Modifier.PUBLIC}) 
    @us.terebi.lang.lpc.runtime.jvm.LpcMemberType(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.MIXED, depth=0)
    LpcValue hoozit_( @us.terebi.lang.lpc.runtime.jvm.LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, depth=0, name="s", semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.BY_VALUE) LpcValue _p_s_v
                             , @us.terebi.lang.lpc.runtime.jvm.LpcParameter(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, depth=0, name="o", semantics=us.terebi.lang.lpc.runtime.ArgumentSemantics.BY_VALUE) LpcValue _p_o_v )
    {
        final LpcVariable _p_s = new LpcVariable( "s", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.STRING, 0) , _p_s_v);
        final LpcVariable _p_o = new LpcVariable( "o", withType( us.terebi.lang.lpc.runtime.LpcType.Kind.OBJECT, 0) , _p_o_v);
        final LpcReferenceValue _lpc_v2 = new us.terebi.lang.lpc.runtime.jvm.value.ReferenceValue(_p_s);
        final LpcValue _lpc_v3 = fuzz_(_lpc_v2);
        final LpcValue _lpc_v4 = MathSupport.add(_p_s.get(),_p_o.get());
        return _lpc_v4;
    } 
}

