package us.terebi.lang.lpc.test;

import java.util.*;
import us.terebi.lang.lpc.runtime.*;
import us.terebi.lang.lpc.runtime.jvm.*;
import us.terebi.lang.lpc.runtime.jvm.support.*;

/** Automatically generated by us.terebi.lang.lpc.compiler.java.JavaCompiler at %%% %%% ## ##:##:## %%% #### for source/lpc/test/us/terebi/lang/lpc/compiler/java/switch_case.c */
public class switch_case extends LpcObject
{
    public @LpcMethod(name="test", modifiers={})
    @LpcReturn(kind=us.terebi.lang.lpc.runtime.LpcType.Kind.INT, depth=0)
    LpcValue test_( )
    {
final LpcValue _lpc_v1 = makeValue(1);
final LpcValue _lpc_v2 = makeValue(0);
final LpcValue _lpc_v3 = makeValue(1);
final LpcValue _lpc_v4 = makeValue(2);
final LpcValue _lpc_v5 = makeValue(4);
final LpcValue _lpc_v6 = makeValue(5);
final LpcValue _lpc_v7 = makeValue(6);
final LpcValue _lpc_v8 = makeValue(7);
final LpcValue _lpc_v9 = makeValue(8);
int _lpc_v10 = -1;
if(_lpc_v2.equals(_lpc_v1)) _lpc_v10=1;
else if(_lpc_v3.equals(_lpc_v1)) _lpc_v10=2;
else if(ComparisonSupport.isInRange(_lpc_v4,_lpc_v5,_lpc_v1)) _lpc_v10=3;
else if(_lpc_v6.equals(_lpc_v1)) _lpc_v10=4;
else if(_lpc_v7.equals(_lpc_v1)) _lpc_v10=5;
else if(ComparisonSupport.isInRange(_lpc_v8,_lpc_v9,_lpc_v1)) _lpc_v10=6;
else _lpc_v10=7;
switch(_lpc_v10)
{
    case 1 :
        final LpcValue _lpc_v11 = makeValue(97);
        return _lpc_v11;
    case 2 :
        final LpcValue _lpc_v12 = makeValue(98);
        return _lpc_v12;
    case 3 :
        final LpcValue _lpc_v13 = makeValue(99);
        return _lpc_v13;
    case 4 :
    case 5 :
    case 6 :
        final LpcValue _lpc_v14 = makeValue(100);
        return _lpc_v14;
    case 7 :
        final LpcValue _lpc_v15 = makeValue(101);
        return _lpc_v15;
    default: throw new us.terebi.lang.lpc.runtime.jvm.exception.LpcRuntimeException("Internal Error - case table did not match");
}
/* 'switch'@4.5 */
    } 
}

